import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro', // The main intro page
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Important information to get started with the textbook.',
      },
      items: [
        'hardware-setup', // Hardware setup guide
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      link: { type: 'doc', id: 'module1-ros2/ros2-fundamentals' }, // Link to the first doc in the module
      items: [{type: 'autogenerated', dirName: 'module1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      link: { type: 'doc', id: 'module2-digital-twin/simulation-basics' },
      items: [{type: 'autogenerated', dirName: 'module2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      link: { type: 'doc', id: 'module3-nvidia-isaac/isaac-perception' },
      items: [{type: 'autogenerated', dirName: 'module3-nvidia-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Capstone',
      link: { type: 'doc', id: 'module4-vla-capstone/vla-integration' },
      items: [{type: 'autogenerated', dirName: 'module4-vla-capstone'}],
    },
  ],
};

export default sidebars;
